/research/dept7/glchen/miniconda3/envs/guojin/bin/python test_l2.py \
--gpu_ids 0 \
--dataroot /research/dept7/glchen/datasets/dlsopc_datasets/pix2l2rect/orect2pixhd_e100_1024_good_dr2mg_D1d1_CALI/dls \
--results_dir /research/dept7/glchen/github/pix2pixHD/l2cali_results \
--resize_or_crop none \
--name orect2pixhd_e100_1024_good_dr2mg_D1d1 \
--loadSize 1024 \
--fineSize 1024 \
--which_epoch latest \
--how_many 10000 \
--norm instance \
--label_nc 0 \
--no_instance \
--zip_and_send \
